# Generated by Django 5.1.4 on 2024-12-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='mentee_initiated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connection',
            name='mentor_initiated',
            field=models.BooleanField(default=False),
        ),
    ]
